"""Added user_message column to chat_history

Revision ID: 2d50f5daf318
Revises: c25ee5a714c0
Create Date: 2025-02-12 03:04:13.547908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d50f5daf318'
down_revision = 'c25ee5a714c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('bot_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('messages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('bot_message')
        batch_op.drop_column('user_message')

    # ### end Alembic commands ###
