"""Initial migration

Revision ID: 769bb7db7b56
Revises: d17a2d0037aa
Create Date: 2025-02-12 02:07:25.871714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769bb7db7b56'
down_revision = 'd17a2d0037aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
